find_package(CGAL COMPONENTS ${CGAL_REQUIRED_COMPONENTS_BY_MODULE} REQUIRED)

list(APPEND ALL_LIBRARIES ${CGAL_LIBRARY} ${GMP_LIBRARIES} ${MPFR_LIBRARIES})
list(APPEND ALL_INCLUDE_DIRECTORIES ${CGAL_INCLUDE_DIRS})